plugins{
    id 'java'
}

group='com.automation'
version='1.0-SNAPSHOT'

java {
    toolchain{
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories{
    mavenCentral()
}

dependencies{
    implementation "org.seleniumhq.selenium:selenium-java:${selenium}"
    implementation "org.junit.jupiter:junit-jupiter-api:${junit}"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitEngine}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitLauncher}"
}

test {
    useJUnitPlatform()
}