plugins{
    id 'java'
}

group='com.automation'
version='1.0-SNAPSHOT'

java {
    toolchain{
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories{
    mavenCentral()
}

dependencies{
    implementation "org.seleniumhq.selenium:selenium-java:${selenium}"
    implementation "org.junit.jupiter:junit-jupiter-api:${junit}"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:${junitEngine}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitLauncher}"
}

test {
    useJUnitPlatform()

    testLogging{
        events "started","passed","failed","skipped","standardOut"

        exceptionFormat="full"
        showCauses=true
        showExceptions=true
        showStackTraces=true
    }

    systemProperty "env", System.getProperty("env", "qa")
    systemProperty "browser", System.getProperty("browser", "chrome")
    systemProperty "headless", System.getProperty("headless","true")
}