#============================
# Environment
#============================

execution.type=local

#============================
# UI
#============================

base.url=http://localhost:8080
browser=chrome
headless=true

#============================
# UI Timeouts
#============================

implicit.wait=0
explicit.wait=30
page.load.timeout=30
script.timeout=30

#============================
# API
#============================

api.base.url=http://localhost:8080
api.base.path=/web/index.php/api/v2

# ==========================
# Authentication
# ==========================

api.auth.type=oauth2
api.auth.token.path=/oauth2/token

# ==========================
# API Timeouts
# ==========================

api.connection.timeout.seconds=30
api.response.timeout.seconds=30
api.request.timeout.seconds=30